
import { Language } from './types';

export const translations = {
  [Language.ENGLISH]: {
    appName: "RailTrack360",
    loginTitle: "Select Your Role",
    operator: "Operator",
    supervisor: "Supervisor",
    maintenance: "Maintenance",
    login: "Login",
    dashboard: "Dashboard",
    verifiedToday: "Verified Today",
    mismatches: "Mismatches",
    pendingReports: "Pending Reports",
    scan: "Scan",
    reportIssue: "Report Issue",
    history: "History",
    scanTitle: "Scan QR / RFID",
    scanSubtitle: "Align the code within the frame to scan.",
    simulatingScan: "Simulating Scan...",
    scanSuccess: "Scan Successful!",
    uid: "UID",
    componentType: "Component Type",
    vendor: "Vendor",
    installationDate: "Installation Date",
    warranty: "Warranty",
    verifyInstallation: "Verify Installation",
    issueType: "Issue Type",
    severity: "Severity",
    uploadPhoto: "Upload Photo",
    submitReport: "Submit Report",
    inspectionLogs: "Inspection Logs",
    // Web Portal
    totalSleepers: "Total Sleepers Received",
    verifiedInstallations: "Verified Installations",
    warrantyExpiring: "Warranty Expiring Soon",
    vendorFailureRate: "Vendor Failure Rate",
    inventory: "Inventory",
    analytics: "AI Analytics",
    warrantyClaims: "Warranty Claims",
    zoneFailureHeatmap: "Zone-wise Failure Heatmap",
    vendorFailureTrends: "Vendor Failure Trends",
    componentLifespan: "Component Lifespan Prediction",
    safetyRiskIndex: "Safety Risk Index",
    generateClaim: "Generate Warranty Claim",
  },
  [Language.HINDI]: {
    appName: "रेलट्रैक360",
    loginTitle: "अपनी भूमिका चुनें",
    operator: "ऑपरेटर",
    supervisor: "सुपरवाइज़र",
    maintenance: "रखरखाव",
    login: "लॉग इन करें",
    dashboard: "डैशबोर्ड",
    verifiedToday: "आज सत्यापित",
    mismatches: "बेमेल",
    pendingReports: "लंबित रिपोर्ट",
    scan: "स्कैन",
    reportIssue: "समस्या की रिपोर्ट करें",
    history: "इतिहास",
    scanTitle: "क्यूआर / आरएफआईडी स्कैन करें",
    scanSubtitle: "स्कैन करने के लिए कोड को फ्रेम के भीतर संरेखित करें।",
    simulatingScan: "स्कैन का अनुकरण किया जा रहा है...",
    scanSuccess: "स्कैन सफल!",
    uid: "यूआईडी",
    componentType: "घटक प्रकार",
    vendor: "विक्रेता",
    installationDate: "स्थापना तिथि",
    warranty: "वारंटी",
    verifyInstallation: "स्थापना सत्यापित करें",
    issueType: "समस्या का प्रकार",
    severity: "गंभीरता",
    uploadPhoto: "फोटो अपलोड करें",
    submitReport: "रिपोर्ट सबमिट करें",
    inspectionLogs: "निरीक्षण लॉग",
    // Web Portal
    totalSleepers: "कुल स्लीपर प्राप्त हुए",
    verifiedInstallations: "सत्यापित स्थापनाएं",
    warrantyExpiring: "वारंटी जल्द ही समाप्त हो रही है",
    vendorFailureRate: "विक्रेता विफलता दर",
    inventory: "इन्वेंटरी",
    analytics: "एआई एनालिटिक्स",
    warrantyClaims: "वारंटी दावे",
    zoneFailureHeatmap: "जोन-वार विफलता हीटमैप",
    vendorFailureTrends: "विक्रेता विफलता रुझान",
    componentLifespan: "घटक जीवनकाल की भविष्यवाणी",
    safetyRiskIndex: "सुरक्षा जोखिम सूचकांक",
    generateClaim: "वारंटी दावा उत्पन्न करें",
  }
};
